package mypojo;
// Generated Sep 24, 2021 7:49:16 AM by Hibernate Tools 4.3.1

import java.util.List;
import java.util.Map;
import javax.faces.bean.ManagedBean;
import mydao.DAOBuku;




/**
 * TblBuku generated by hbm2java
 */
@ManagedBean
public class TblBuku  implements java.io.Serializable {


     private String idBuku;
     private String judul;
     private String penulisId;
     private String penerbitId;
     private String genreId;
     private String sinopsis;
     private double harga;
     private int stok;
     
     private Boolean error = false;
     private String errorMsg = "";

    public TblBuku() {
    }

    public TblBuku(String idBuku, String judul, String penulisId, String penerbitId, String genreId, String sinopsis, double harga, int stok) {
       this.idBuku = idBuku;
       this.judul = judul;
       this.penulisId = penulisId;
       this.penerbitId = penerbitId;
       this.genreId = genreId;
       this.sinopsis = sinopsis;
       this.harga = harga;
       this.stok = stok;
    }

    public Boolean getError() {
        return error;
    }

    public void setError(Boolean error) {
        this.error = error;
    }

    public String getErrorMsg() {
        return errorMsg;
    }

    public void setErrorMsg(String errorMsg) {
        this.errorMsg = errorMsg;
    }
   
    public String getIdBuku() {
        return this.idBuku;
    }
    
    public void setIdBuku(String idBuku) {
        this.idBuku = idBuku;
    }
    public String getJudul() {
        return this.judul;
    }
    
    public void setJudul(String judul) {
        this.judul = judul;
    }
    public String getPenulisId() {
        return this.penulisId;
    }
    
    public void setPenulisId(String penulisId) {
        this.penulisId = penulisId;
    }
    public String getPenerbitId() {
        return this.penerbitId;
    }
    
    public void setPenerbitId(String penerbitId) {
        this.penerbitId = penerbitId;
    }
    public String getGenreId() {
        return this.genreId;
    }
    
    public void setGenreId(String genreId) {
        this.genreId = genreId;
    }
    public String getSinopsis() {
        return this.sinopsis;
    }
    
    public void setSinopsis(String sinopsis) {
        this.sinopsis = sinopsis;
    }
    public double getHarga() {
        return this.harga;
    }
    
    public void setHarga(double harga) {
        this.harga = harga;
    }
    public int getStok() {
        return this.stok;
    }
    
    public void setStok(int stok) {
        this.stok = stok;
    }
    public String addData() {
        DAOBuku dao = new DAOBuku();
        List isi = dao.getById(idBuku);
        if(isi.isEmpty()) {
            dao.add(this);
            idBuku = "";
            judul = "";
            penulisId = "";
            penerbitId = "";
            genreId = "";
            sinopsis = "";
            harga = 0;
            stok = 0;
            return "/admin/buku?faces-redirect=true";
        }
        error = true;
        errorMsg = "ID Has been Taken.!";
        return "";
    }
    public String updData() {
        DAOBuku dao = new DAOBuku();
        dao.upd(this);
        idBuku = "";
        judul = "";
        penulisId = "";
        penerbitId = "";
        genreId = "";
        sinopsis = "";
        harga = 0;
        stok = 0;
        return "/admin/buku?faces-redirect=true";
    }
    public String delData(String idnya) {
        DAOBuku dao = new DAOBuku();
        dao.del(idnya);
        return "/admin/buku?faces-redirect=true";
    }
    
    public List<Map<String, Object>> getAllData() {
        DAOBuku dao = new DAOBuku();
        return dao.getAll();
    }
    public String showEdit(String idnya) {
        DAOBuku dao = new DAOBuku();
        List<Map<String, Object>> isi = dao.getById(idnya);
        idBuku = isi.get(0).get("id_buku").toString();
        judul = isi.get(0).get("judul").toString();
        penulisId = isi.get(0).get("penulis_id").toString();
        penerbitId = isi.get(0).get("penerbit_id").toString();
        genreId = isi.get(0).get("genre_id").toString();
        sinopsis = isi.get(0).get("sinopsis").toString();
        harga = Double.parseDouble(isi.get(0).get("harga").toString());
        stok = Integer.parseInt(isi.get(0).get("stok").toString());
        return "buku-edit.xhtml";
    }
    
//    public List cobaMuntahin() {
//        DAOBuku
//    }



}


