package mypojo;
// Generated Sep 24, 2021 7:49:16 AM by Hibernate Tools 4.3.1

import javax.faces.bean.ManagedBean;




/**
 * TblDetTrx generated by hbm2java
 */
@ManagedBean
public class TblDetTrx  implements java.io.Serializable {


     private TblDetTrxId id;
     private int qty;
     private double harga;
     private String trxId;

    public TblDetTrx() {
    }

    public TblDetTrx(TblDetTrxId id, int qty, double harga) {
       this.id = id;
       this.qty = qty;
       this.harga = harga;
    }

    public String getTrxId() {
        return trxId;
    }

    public void setTrxId(String trxId) {
        this.trxId = trxId;
    }
   
    public TblDetTrxId getId() {
        return this.id;
    }
    
    public void setId(TblDetTrxId id) {
        this.id = id;
    }
    public int getQty() {
        return this.qty;
    }
    
    public void setQty(int qty) {
        this.qty = qty;
    }
    public double getHarga() {
        return this.harga;
    }
    
    public void setHarga(double harga) {
        this.harga = harga;
    }




}


