package mypojo;
// Generated Sep 24, 2021 7:49:16 AM by Hibernate Tools 4.3.1



/**
 * TblDetTrxId generated by hbm2java
 */
public class TblDetTrxId  implements java.io.Serializable {


     private String trxId;
     private String bukuId;

    public TblDetTrxId() {
    }

    public TblDetTrxId(String trxId, String bukuId) {
       this.trxId = trxId;
       this.bukuId = bukuId;
    }
   
    public String getTrxId() {
        return this.trxId;
    }
    
    public void setTrxId(String trxId) {
        this.trxId = trxId;
    }
    public String getBukuId() {
        return this.bukuId;
    }
    
    public void setBukuId(String bukuId) {
        this.bukuId = bukuId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TblDetTrxId) ) return false;
		 TblDetTrxId castOther = ( TblDetTrxId ) other; 
         
		 return ( (this.getTrxId()==castOther.getTrxId()) || ( this.getTrxId()!=null && castOther.getTrxId()!=null && this.getTrxId().equals(castOther.getTrxId()) ) )
 && ( (this.getBukuId()==castOther.getBukuId()) || ( this.getBukuId()!=null && castOther.getBukuId()!=null && this.getBukuId().equals(castOther.getBukuId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getTrxId() == null ? 0 : this.getTrxId().hashCode() );
         result = 37 * result + ( getBukuId() == null ? 0 : this.getBukuId().hashCode() );
         return result;
   }   


}


