package mypojo;
// Generated Sep 24, 2021 7:49:16 AM by Hibernate Tools 4.3.1

import java.util.List;
import javax.faces.bean.ManagedBean;
import mydao.DAOGenre;




/**
 * TblGenre generated by hbm2java
 */
@ManagedBean
public class TblGenre  implements java.io.Serializable {


     private String idGenre;
     private String nama;
     private String keterangan;
     
     private Boolean error = false;
     private String errorMsg = "";
    public TblGenre() {
    }

    public TblGenre(String idGenre, String nama, String keterangan) {
       this.idGenre = idGenre;
       this.nama = nama;
       this.keterangan = keterangan;
    }

    public Boolean getError() {
        return error;
    }

    public void setError(Boolean error) {
        this.error = error;
    }

    public String getErrorMsg() {
        return errorMsg;
    }

    public void setErrorMsg(String errorMsg) {
        this.errorMsg = errorMsg;
    }
    
   
    public String getIdGenre() {
        return this.idGenre;
    }
    
    public void setIdGenre(String idGenre) {
        this.idGenre = idGenre;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public String getKeterangan() {
        return this.keterangan;
    }
    
    public void setKeterangan(String keterangan) {
        this.keterangan = keterangan;
    }

    public String addData() {
        DAOGenre dao = new DAOGenre();
        List isi = dao.getById(idGenre);
        if(isi.isEmpty()) {
            dao.add(this);
            idGenre = "";
            nama = "";
            keterangan = "";
            return "/admin/genre?faces-redirect=true";
        }
        error = true;
        errorMsg = "ID Has been Taken.!";
        return "";
    }
    public String updData() {
        System.out.println(this.idGenre);
        DAOGenre dao = new DAOGenre();
        dao.upd(this);
        idGenre = "";
        nama = "";
        keterangan = "";
        return "/admin/genre?faces-redirect=true";
    }
    public String delData(String idnya) {
        DAOGenre dao = new DAOGenre();
        dao.del(idnya);
        return "/admin/genre?faces-redirect=true";
    }
    public List<TblGenre> getById(String idnya) {
        DAOGenre dao = new DAOGenre();
        List<TblGenre> isi = dao.getById(idnya);
        return isi;
    }
    public List<TblGenre> getAllData() {
        DAOGenre dao = new DAOGenre();
        return dao.getAll();
    }
    public String showEdit(String idnya) {
        DAOGenre dao = new DAOGenre();
        List<TblGenre> isi = dao.getById(idnya);
        idGenre = isi.get(0).getIdGenre();
        nama = isi.get(0).getNama();
        keterangan = isi.get(0).getKeterangan();
        return "buku-edit.xhtml";
    }
//    public List getAllData() {
//        DAOGenre dao = new DAOGenre();
//        return dao.getAll();
//    }


}


