package mypojo;
// Generated Sep 24, 2021 7:49:16 AM by Hibernate Tools 4.3.1

import java.util.List;
import javax.faces.bean.ManagedBean;
import mydao.DAOPenerbit;




/**
 * TblPenerbit generated by hbm2java
 */
@ManagedBean
public class TblPenerbit  implements java.io.Serializable {


     private String idPenerbit;
     private String nama;
     private String alamat;
     private String noTelp;
     private String email;
     
     private Boolean error = false;
     private String errorMsg = "";
    public TblPenerbit() {
    }

    public TblPenerbit(String idPenerbit, String nama, String alamat, String noTelp, String email) {
       this.idPenerbit = idPenerbit;
       this.nama = nama;
       this.alamat = alamat;
       this.noTelp = noTelp;
       this.email = email;
    }

    public Boolean getError() {
        return error;
    }

    public void setError(Boolean error) {
        this.error = error;
    }

    public String getErrorMsg() {
        return errorMsg;
    }

    public void setErrorMsg(String errorMsg) {
        this.errorMsg = errorMsg;
    }
    
   
    public String getIdPenerbit() {
        return this.idPenerbit;
    }
    
    public void setIdPenerbit(String idPenerbit) {
        this.idPenerbit = idPenerbit;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public String getAlamat() {
        return this.alamat;
    }
    
    public void setAlamat(String alamat) {
        this.alamat = alamat;
    }
    public String getNoTelp() {
        return this.noTelp;
    }
    
    public void setNoTelp(String noTelp) {
        this.noTelp = noTelp;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    public String addData() {
        DAOPenerbit dao = new DAOPenerbit();
        List isi = dao.getById(idPenerbit);
        if(isi.isEmpty()) {
            dao.add(this);
            idPenerbit = "";
            nama = "";
            alamat = "";
            noTelp = "";
            email = "";
            return "/admin/penerbit?faces-redirect=true";
        }
        error = true;
        errorMsg = "ID Has been Taken.!";
        return "";
    }
    public String updData() {
        System.out.println(this.idPenerbit);
        DAOPenerbit dao = new DAOPenerbit();
        dao.upd(this);
        idPenerbit = "";
        nama = "";
        alamat = "";
        noTelp = "";
        email = "";
        return "/admin/penerbit?faces-redirect=true";
    }
    public String delData(String idnya) {
        DAOPenerbit dao = new DAOPenerbit();
        dao.del(idnya);
        return "/admin/penerbit?faces-redirect=true";
    }
    public List<TblPenerbit> getAllData() {
        DAOPenerbit dao = new DAOPenerbit();
        return dao.getAll();
    }
    public List<TblPenerbit> getById(String idnya) {
        DAOPenerbit dao = new DAOPenerbit();
        List<TblPenerbit> isi = dao.getById(idnya);
        return isi;
    }
    public String showEdit(String idnya) {
        DAOPenerbit dao = new DAOPenerbit();
        List<TblPenerbit> isi = dao.getById(idnya);
        idPenerbit = isi.get(0).getIdPenerbit();
        nama = isi.get(0).getNama();
        alamat = isi.get(0).getAlamat();
        noTelp = isi.get(0).getNoTelp();
        email = isi.get(0).getEmail();
        return "penerbit-edit.xhtml";
    }


}


