package mypojo;
// Generated Sep 24, 2021 7:49:16 AM by Hibernate Tools 4.3.1

import java.util.List;
import javax.faces.bean.ManagedBean;
import mydao.DAOPelanggan;




/**
 * TblPelanggan generated by hbm2java
 */
@ManagedBean
public class TblPelanggan  implements java.io.Serializable {


     private String idPelanggan;
     private String nama;
     private String alamat;
     private String noTelp;
     private String email;
     
     private String msgError = "";
     private Boolean isError = false;
     private Boolean isMsg = false;
     private String msg = "";

    public TblPelanggan() {
    }

    public TblPelanggan(String idPelanggan, String nama, String alamat, String noTelp, String email) {
       this.idPelanggan = idPelanggan;
       this.nama = nama;
       this.alamat = alamat;
       this.noTelp = noTelp;
       this.email = email;
    }

    public Boolean getIsMsg() {
        return isMsg;
    }

    public void setIsMsg(Boolean isMsg) {
        this.isMsg = isMsg;
    }

    public String getMsg() {
        return msg;
    }

    public void setMsg(String msg) {
        this.msg = msg;
    }

    public String getMsgError() {
        return msgError;
    }

    public void setMsgError(String msgError) {
        this.msgError = msgError;
    }

    public Boolean getIsError() {
        return isError;
    }

    public void setIsError(Boolean isError) {
        this.isError = isError;
    }
   
    public String getIdPelanggan() {
        return this.idPelanggan;
    }
    
    public void setIdPelanggan(String idPelanggan) {
        this.idPelanggan = idPelanggan;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public String getAlamat() {
        return this.alamat;
    }
    
    public void setAlamat(String alamat) {
        this.alamat = alamat;
    }
    public String getNoTelp() {
        return this.noTelp;
    }
    
    public void setNoTelp(String noTelp) {
        this.noTelp = noTelp;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    
    public void reset() {
        nama = "";
        alamat = "";
        email = "";
        noTelp = "";
        idPelanggan = "";
    }


    public void save() {
        isError = false;
        msgError = "";
        msg = "";
        isMsg = false;
        
        DAOPelanggan lstplg = new DAOPelanggan();
        List<TblPelanggan> arr = lstplg.getById(idPelanggan);
        
        if(arr.size() > 0) {
            isError = true;
            msgError = "ID Sudah Terpakai.!";
            
        }else {
            DAOPelanggan plg = new DAOPelanggan();
            plg.addPelanggan(this);

            isMsg = true;
            msg = "Success Save Data.!";
            nama = "";
            alamat = "";
            email = "";
            noTelp = "";
            idPelanggan = "";
        }
    }
    
    public void delete() {
        isError = false;
        msgError = "";
        msg = "";
        isMsg = false;
        
        DAOPelanggan plg = new DAOPelanggan();
        plg.delPelanggan(idPelanggan);
        
        nama = "";
        alamat = "";
        email = "";
        noTelp = "";
        idPelanggan = "";
        
        isMsg = true;
        msg = "Success Delete Data.!";
    }
    
    public List<TblPelanggan> getByIdforTrx(String idnya) {
        DAOPelanggan dao = new DAOPelanggan();
        List<TblPelanggan> isi = dao.getById(idnya);
        return isi;
    }
    
    public String getById() {
        nama = "";
        alamat = "";
        email = "";
        noTelp = "";
        isError = false;
        msgError = "";
        msg = "";
        isMsg = false;
        
        DAOPelanggan plg = new DAOPelanggan();
        List<TblPelanggan> arr = plg.getById(idPelanggan);
        System.out.println(arr.size()+" PANJANGNYA ");
        
        if(arr.size() > 0) {
            TblPelanggan isi = arr.get(0);
            nama = isi.getNama();
            alamat = isi.getAlamat();
            email = isi.getEmail();
            noTelp = isi.getNoTelp();
            idPelanggan = isi.getIdPelanggan();
        }else {
            isError = true;
            msgError = "Upss.. Data Not Found.!";
        }
//        return "view_pelanggan";
        return "";
    }
    
    public List<TblPelanggan> getTblPelanggan() {
        DAOPelanggan plg = new DAOPelanggan();
        return plg.getTblPelanggan();
    }
    
    public void update() {
        isError = false;
        msgError = "";
        msg = "";
        isMsg = false;
        
        DAOPelanggan plg = new DAOPelanggan();
        plg.updPelanggan(this);
        
        nama = "";
        alamat = "";
        email = "";
        noTelp = "";
        idPelanggan = "";
        
        isMsg = true;
        msg = "Success Update Data.!";
    }

}


