package mypojo;
// Generated Sep 24, 2021 7:49:16 AM by Hibernate Tools 4.3.1

import java.util.List;
import javax.faces.bean.ManagedBean;
import mydao.DAOPenulis;




/**
 * TblPenulis generated by hbm2java
 */
@ManagedBean
public class TblPenulis  implements java.io.Serializable {


     private String idPenulis;
     private String nama;
     private String alamat;
     private String noTelp;
     private String email;
     
     private Boolean error = false;
     private String errorMsg = "";
    public TblPenulis() {
    }

    public TblPenulis(String idPenulis, String nama, String alamat, String noTelp, String email) {
       this.idPenulis = idPenulis;
       this.nama = nama;
       this.alamat = alamat;
       this.noTelp = noTelp;
       this.email = email;
    }

    public Boolean getError() {
        return error;
    }

    public void setError(Boolean error) {
        this.error = error;
    }

    public String getErrorMsg() {
        return errorMsg;
    }

    public void setErrorMsg(String errorMsg) {
        this.errorMsg = errorMsg;
    }
    
   
    public String getIdPenulis() {
        return this.idPenulis;
    }
    
    public void setIdPenulis(String idPenulis) {
        this.idPenulis = idPenulis;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public String getAlamat() {
        return this.alamat;
    }
    
    public void setAlamat(String alamat) {
        this.alamat = alamat;
    }
    public String getNoTelp() {
        return this.noTelp;
    }
    
    public void setNoTelp(String noTelp) {
        this.noTelp = noTelp;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    public String addData() {
        DAOPenulis dao = new DAOPenulis();
        List isi = dao.getById(idPenulis);
        if(isi.isEmpty()) {
            dao.add(this);
            idPenulis = "";
            nama = "";
            alamat = "";
            noTelp = "";
            email = "";
            return "/admin/penulis?faces-redirect=true";
        }
        error = true;
        errorMsg = "ID Has been Taken.!";
        return "";
    }
    public String updData() {
        DAOPenulis dao = new DAOPenulis();
        dao.upd(this);
        idPenulis = "";
        nama = "";
        alamat = "";
        noTelp = "";
        email = "";
        return "/admin/penulis?faces-redirect=true";
    }
    public String delData(String idnya) {
        DAOPenulis dao = new DAOPenulis();
        dao.del(idnya);
        return "/admin/penulis?faces-redirect=true";
    }
    public List<TblPenulis> getAllData() {
        DAOPenulis dao = new DAOPenulis();
        return dao.getAll();
    }
    public List<TblPenulis> getById(String idnya) {
        DAOPenulis dao = new DAOPenulis();
        List<TblPenulis> isi = dao.getById(idnya);
        return isi;
    }
    public String showEdit(String idnya) {
        DAOPenulis dao = new DAOPenulis();
        List<TblPenulis> isi = dao.getById(idnya);
        idPenulis = isi.get(0).getIdPenulis();
        nama = isi.get(0).getNama();
        alamat = isi.get(0).getAlamat();
        noTelp = isi.get(0).getNoTelp();
        email = isi.get(0).getEmail();
        return "penulis-edit.xhtml";
    }


}


