package mypojo;
// Generated Sep 24, 2021 7:49:16 AM by Hibernate Tools 4.3.1

import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;
import mydao.DAOLogin;
import mydao.DAOUser;




/**
 * TblUser generated by hbm2java
 */
@ManagedBean
public class TblUser  implements java.io.Serializable {


     private Integer idUser;
     private String username;
     private String password;
     private String role;
     
     private Boolean error = false;
     private String errorMsg = "";
    public TblUser() {
    }

    public TblUser(String username, String password, String role) {
       this.username = username;
       this.password = password;
       this.role = role;
    }

    public Boolean getError() {
        return error;
    }

    public void setError(Boolean error) {
        this.error = error;
    }

    public String getErrorMsg() {
        return errorMsg;
    }

    public void setErrorMsg(String errorMsg) {
        this.errorMsg = errorMsg;
    }
    
    
    
   
    public Integer getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(Integer idUser) {
        this.idUser = idUser;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }
    public String delData(String idnya) {
        DAOUser dao = new DAOUser();
        dao.del(idnya);
        return "/admin/user?faces-redirect=true";
    }
    
    public List<TblUser> getAllData() {
        DAOUser dao = new DAOUser();
        return dao.getAll();
    }
    
    public String logout() {
        HttpServletRequest request = (HttpServletRequest) FacesContext.getCurrentInstance().getExternalContext().getRequest();
        HttpSession session = request.getSession();
        session.invalidate();
        return "/index?faces-redirect=true";
    }
    public String validasiLogin() {
        DAOLogin daoLogin = new DAOLogin();
        List<TblUser> tblUsr = daoLogin.getBy(username, password);
        System.out.println(tblUsr);
        if(tblUsr.size() == 1){
            System.out.println("MASUK COYY");
            username = tblUsr.get(0).username;
            password = tblUsr.get(0).password;
            role = tblUsr.get(0).role;
            HttpServletRequest request = (HttpServletRequest) FacesContext.getCurrentInstance().getExternalContext().getRequest();
            HttpSession session = request.getSession();
            session.setAttribute("login", true);
            session.setAttribute("datalogin", this);
            if(role.equals("admin")) {
                return "admin/dashboard?faces-redirect=true";
            }
            return "user/dashboard?faces-redirect=true";
        }
        error = true;
        errorMsg = "Username or Password Incorrect!!";
        System.out.println("TIDAK MASUK");
        return "index";
    }
    
    public String registed() {
        DAOUser daousr = new DAOUser();
        List isi = daousr.getById(username);
        if(isi.isEmpty()) {
            role = "user";
            daousr.add(this);
            return "index?faces-redirect=true";
        }
        error = true;
        errorMsg = "Userid is Taken.!";
        return "register";
    }




}


